Import('qt_env')

env = qt_env.Clone()

modules = [
    'Core',
    'Gui'
]

if env['QT_MAJOR_VERSION'] > 4:
    modules += [ 'Widgets' ]

env.EnableQt4Modules(['Qt' + n for n in modules],
                     debug = env['CONFIG'] == 'debug')

env.AppendUnique(CPPDEFINES = [ 'PREVIEWBASE_LIBRARY' ])

env.RequireLibraries('uibase')

lib = env.SharedLibrary('previewBase', env.Glob('*.cpp'))
env.InstallPlugin(lib)
