Import('qt_env')

env = qt_env.Clone()

env.AppendUnique(CPPDEFINES = [ 'PREVIEWBSA_LIBRARY' ])

lib = env.SharedLibrary('previewBsa', env.Glob('*.cpp'))
env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
